#!/bin/bash
log="log location"
echo "Starting run on " | tr -d '\n'  >> $log
date +"%d.%m.%Y %R" | tr -d '\n'  >> $log
echo " " | tr -d '\n'  >> $log
your command goes here | tr '\n' ' '  >> $log
echo "Completed on " | tr -d '\n'  >> $log
date +"%d.%m.%Y %R" >> $log
